import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const OWNER_KEY_RE=/^[0-9a-f]{64}$/i;
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:H});
const clamp=(s:string,n=4000)=>s.replace(/\u0000/g,"").slice(0,n);
const driveId=(u:string|null|undefined)=>{if(!u)return null;const m=u.match(/\/d\/([^/?#]+)/)||u.match(/[?&]id=([^&#]+)/);return m?.[1]??null;};
const norm=(s:string)=>s.normalize("NFKC").toLowerCase().replace(/[\s　:：・.．、\-–—()（）_「」『』【】!?！？]/g,"");
const titleCore=(s:string)=>norm(s.replace(/^第\s*[0-9０-９一二三四五六七八九十百]+\s*章\s*/u,"").replace(/^[0-9０-９]{1,2}[.)．、]\s*/u,""));
function grams(s:string,n=2){const a=[...norm(s)],out=new Set<string>();for(let i=0;i<=a.length-n;i++)out.add(a.slice(i,i+n).join(""));return out;}
function fuzzyScore(q:string,t:string){const nq=norm(q),nt=norm(t),core=titleCore(t);if(!nq||!nt)return 0;if(core.length>=2&&nq.includes(core))return 1.25;if(nt.length>=2&&nq.includes(nt))return 1.18;const qg=grams(q),tg=grams(core||t);if(!qg.size||!tg.size)return 0;let hit=0;for(const g of tg)if(qg.has(g))hit++;return Math.min(.92,hit/Math.max(1,tg.size));}
function nodeScore(q:string,n:any){let s=fuzzyScore(q,String(n.title??""));for(const c of n.children??[])s=Math.max(s,fuzzyScore(q,String(c.title??""))*1.06);return Math.max(s,fuzzyScore(q,String(n.summary??""))*.4);}
function deepIntent(q:string){return /(第?\s*\d+\s*章|章|節|マニュアル|教科書|辞典|規約|資料|PDF|レポート|文書|ドキュメント|何ページ|どこに書|横断|全体|比較|言い換え|LINE返信|セッション)/i.test(q);}
function outputText(j:any){if(typeof j?.output_text==="string")return j.output_text;const p:string[]=[];for(const o of j?.output??[])for(const c of o?.content??[])if(c?.type==="output_text"&&typeof c?.text==="string")p.push(c.text);return p.join("\n").trim();}
async function callOpenAI(k:string,m:string,inst:string,input:string,max=1400){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${k}`,"content-type":"application/json"},body:JSON.stringify({model:m,instructions:inst,input,max_output_tokens:max})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`openai_${r.status}`);return outputText(j);}
type Ev={label:string;title:string;url:string|null;text:string;grounding:string;node_id:string|null;drive_file_id:string|null;page_start?:number|null;page_end?:number|null;deep_node_id?:string|null;score?:number|null};

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"});
 const sbUrl=Deno.env.get("SUPABASE_URL"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!sbUrl||!serviceKey)return json(500,{ok:false,error:"supabase_credentials_missing"});
 try{
  const body=await req.json().catch(()=>({})),ownerKey=String(body?.owner_key??"").trim(),question=String(body?.question??"").trim();
  const requestedAnswer=body?.answer_mode==="retrieve"?"retrieve":"ai",requestedRoute=["auto","deep","standard"].includes(body?.retrieval_mode)?body.retrieval_mode:"auto";
  if(!OWNER_KEY_RE.test(ownerKey))return json(401,{ok:false,error:"owner_auth_required"});if(question.length<2)return json(400,{ok:false,error:"question_required"});
  const db=createClient(sbUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data:auth}=await db.rpc("masa_evidence_owner_ok_v1",{p_owner_key:ownerKey});if(auth!==true)return json(403,{ok:false,error:"owner_auth_failed"});
  const {data:search,error:sErr}=await db.rpc("knowledge_fabric_search_v2",{p_query:question,p_query_embedding:null,p_embedding_model:null,p_limit:16});if(sErr)throw sErr;
  const base=(search??[]).filter((x:any)=>!String(x.status??"").toLowerCase().includes("deprecated")),ids=base.map((x:any)=>x.node_id);
  const {data:nodes,error:nErr}=ids.length?await db.from("knowledge_fabric_nodes").select("id,source_table,source_id,title,canonical_url,canonical_priority,metadata").in("id",ids):{data:[],error:null};if(nErr)throw nErr;const byId=new Map((nodes??[]).map((n:any)=>[n.id,n]));
  const dIds=[...new Set(base.map((x:any)=>driveId(x.canonical_url)).filter(Boolean))] as string[],cIds=(nodes??[]).filter((n:any)=>n.source_table==="knowledge_canonical_snapshots").map((n:any)=>n.source_id);let snaps:any[]=[];
  if(dIds.length){const {data,error}=await db.from("knowledge_canonical_snapshots").select("id,drive_file_id,title,canonical_url,content,content_hash,metadata").in("drive_file_id",dIds);if(error)throw error;snaps.push(...(data??[]));}
  if(cIds.length){const {data,error}=await db.from("knowledge_canonical_snapshots").select("id,drive_file_id,title,canonical_url,content,content_hash,metadata").in("id",cIds);if(error)throw error;for(const x of data??[])if(!snaps.some(y=>y.id===x.id))snaps.push(x);}
  const byDrive=new Map(snaps.map((s:any)=>[s.drive_file_id,s])),bySnap=new Map(snaps.map((s:any)=>[s.id,s]));
  const ranked=base.map((r:any)=>{const n:any=byId.get(r.node_id),did=n?.source_table==="knowledge_canonical_snapshots"?bySnap.get(n.source_id)?.drive_file_id:driveId(r.canonical_url),snap=did?byDrive.get(did):null;return {...r,node:n,drive_file_id:did??null,snapshot:snap??null,rank_score:Number(r.final_score??0)+(snap?.content?.length>100?.22:0)+(String(n?.canonical_priority??"").toUpperCase()==="S"?.05:0)};}).sort((a:any,b:any)=>b.rank_score-a.rank_score).slice(0,8);
  const readyIds=[...new Set(ranked.map((x:any)=>x.drive_file_id).filter(Boolean))] as string[];let indexes:any[]=[];if(readyIds.length){const {data,error}=await db.from("knowledge_deep_indexes").select("id,drive_file_id,source_node_id,title,canonical_url,provider,tree,source_chars,status,index_version").in("drive_file_id",readyIds).eq("status","ready");if(error)throw error;indexes=data??[];}
  const pr=(p:string)=>p==="pageindex_cloud"?3:p==="pageindex_local"?2:1;indexes.sort((a:any,b:any)=>pr(b.provider)-pr(a.provider));const deep=indexes.map((i:any)=>({...i,r:ranked.find((x:any)=>x.drive_file_id===i.drive_file_id),query_score:ranked.find((x:any)=>x.drive_file_id===i.drive_file_id)?.rank_score??0})).sort((a:any,b:any)=>b.query_score-a.query_score),top=deep[0]??null;
  const auto=!!top&&(Number(top.source_chars)>=12000||deepIntent(question)||Number(top.query_score)>=.72),route=requestedRoute==="deep"?(top?"deep":"standard"):requestedRoute==="standard"?"standard":auto?"deep":"standard";let fallback:string|null=requestedRoute==="deep"&&!top?"no_ready_deep_index":null;
  const evidence:Ev[]=[],apiKey=Deno.env.get("OPENAI_API_KEY")||"",model=Deno.env.get("KNOWLEDGE_ANSWER_MODEL")||"gpt-5.6-luna";let selected:string[]=[],selection="standard",selectorReason:string|null=null;
  if(route==="deep"&&top){const snap=byDrive.get(top.drive_file_id),arr=Array.isArray(top.tree?.nodes)?top.tree.nodes:[];if(!snap?.content||!arr.length)fallback="deep_index_missing_source_text";else{const scored=arr.map((n:any)=>({n,score:nodeScore(question,n)})).sort((a:any,b:any)=>b.score-a.score),best=Number(scored[0]?.score??0);selected=scored.filter((x:any,i:number)=>i<4&&x.score>=Math.max(.18,best*.62)).map((x:any)=>x.n.node_id);selection="deterministic_japanese_tree";
   if(apiKey&&requestedAnswer==="ai"&&arr.length>1){try{const view=arr.map((n:any)=>({node_id:n.node_id,title:n.title,children:(n.children??[]).map((c:any)=>c.title),summary:clamp(String(n.summary??""),180)})),raw=await callOpenAI(apiKey,model,"Select the smallest relevant document tree nodes. Return strict JSON only: {\"node_ids\":[\"...\"],\"reason\":\"...\"}. Max 4. Do not answer.",`QUESTION:\n${question}\nTREE:\n${JSON.stringify(view)}`,500),p=JSON.parse(raw.replace(/^```json\s*|```$/g,"").trim()),allow=new Set(arr.map((n:any)=>n.node_id)),llm=(Array.isArray(p?.node_ids)?p.node_ids:[]).filter((x:any)=>allow.has(x)).slice(0,4);if(llm.length){selected=llm;selection="llm_tree_reasoning";}selectorReason=typeof p?.reason==="string"?p.reason.slice(0,300):null;}catch(e){selectorReason="selector_fallback";}}
   if(!selected.length)selected=scored.slice(0,2).map((x:any)=>x.n.node_id);let total=0;for(const id of selected){const n=arr.find((x:any)=>x.node_id===id);if(!n)continue;let text=String(snap.content).slice(Number(n.start_char??0),Number(n.end_char??snap.content.length));if(text.length>7000)text=text.slice(0,7000);if(total+text.length>16000)text=text.slice(0,16000-total);if(!text)continue;total+=text.length;evidence.push({label:`D${evidence.length+1}`,title:`${top.title} — ${n.title}`,url:top.canonical_url,text,grounding:"deep_read_section",node_id:top.source_node_id??null,drive_file_id:top.drive_file_id,page_start:n.page_start??null,page_end:n.page_end??null,deep_node_id:n.node_id,score:nodeScore(question,n)});}}
  }
  if(!evidence.length){for(const r of ranked.slice(0,6)){const n=r.node;let text="",grounding="thin_metadata";if(r.snapshot?.content){text=clamp(String(r.snapshot.content),4200);grounding="canonical_snapshot";}else if(n?.source_table==="knowledge_items"){const {data}=await db.from("knowledge_items").select("content,summary").eq("id",n.source_id).maybeSingle();text=clamp(String(data?.content||data?.summary||""),4200);if(text)grounding="knowledge_item";}else if(n?.source_table==="sources"){const {data}=await db.from("sources").select("raw_text").eq("id",n.source_id).maybeSingle();text=clamp(String(data?.raw_text||""),4200);if(text)grounding="source_text";}if(!text)text=`Title: ${r.title}\nAliases: ${(r.matched_aliases||[]).join(", ")}`;evidence.push({label:`S${evidence.length+1}`,title:r.title,url:r.canonical_url,text,grounding,node_id:r.node_id,drive_file_id:r.drive_file_id});}}
  let answer:any=null,usedModel:string|null=null,effective=requestedAnswer;if(requestedAnswer==="ai"&&apiKey&&evidence.length){const src=evidence.map(e=>`[${e.label}] ${e.title}\n${e.text}`).join("\n\n---\n\n");answer=await callOpenAI(apiKey,model,"Answer in Japanese using only supplied evidence. Cite [D1]/[S1]. State if evidence is partial.",`QUESTION:\n${question}\n\nEVIDENCE:\n${src}`,1800);usedModel=model;}else if(requestedAnswer==="ai"&&!apiKey){effective="retrieve";answer="回答LLM未設定のため、根拠箇所の抽出まで実行しました。sources を回答生成の根拠として使用してください。";}
  const outcome=evidence.length?(fallback?"partial":"success"):"failure";if(top)await db.rpc("knowledge_deep_mark_use_v1",{p_index_id:top.id,p_outcome:outcome});await db.rpc("knowledge_fabric_record_feedback_v1",{p_event_type:"retrieval",p_outcome:outcome,p_observation:`Knowledge Ask v3 route=${route}; selection=${selection}; evidence=${evidence.length}.`,p_query_text:question,p_subject_node_id:top?.source_node_id??ranked[0]?.node_id??null,p_subject_edge_id:null,p_related_rule_key:route==="deep"?"deep_read_router":"hybrid_retrieval",p_expected_result:"Grounded retrieval with fit-based routing.",p_actual_result:`route=${route}; provider=${top?.provider??"none"}; fallback=${fallback??"none"}; answer=${effective}`,p_evidence:evidence.map(e=>({label:e.label,title:e.title,grounding:e.grounding,page_start:e.page_start??null,page_end:e.page_end??null,deep_node_id:e.deep_node_id??null,score:e.score??null})),p_proposed_action:!apiKey&&requestedAnswer==="ai"?"LLM synthesis is optional; retrieval is active without a key.":null,p_actor:"knowledge-ask-v3",p_metadata:{architecture_version:"knowledge-ask-v3.1",route,provider:top?.provider??null,selection_method:selection,selected_node_ids:selected,fallback_reason:fallback,llm_available:!!apiKey,vector_used:false}});
  return json(200,{ok:true,version:"3.1",mode:{requested:requestedAnswer,effective},model:usedModel,answer,route:{requested:requestedRoute,used:route,provider:top?.provider??null,index_version:top?.index_version??null,selection_method:selection,selected_node_ids:selected,selector_reason:selectorReason,fallback_reason:fallback},sources:evidence.map(e=>({label:e.label,title:e.title,url:e.url,grounding:e.grounding,node_id:e.node_id,drive_file_id:e.drive_file_id,page_start:e.page_start??null,page_end:e.page_end??null,deep_node_id:e.deep_node_id??null,score:e.score??null,preview:clamp(e.text,360)})),retrieval_receipt:{query:question,candidates:ranked.length,deep_candidates:deep.length,evidence_count:evidence.length,vector_used:false,llm_available:!!apiKey,architecture:"fabric+deep-read"}});
 }catch(e){console.error("knowledge-ask-v3",e);return json(500,{ok:false,error:"knowledge_ask_v3_failed",detail:e instanceof Error?e.message:String(e)});}
});