create table if not exists public.person_serials (
  person_id uuid primary key references public.contacts(id) on delete cascade,
  serial_no bigint generated by default as identity unique,
  serial_code text generated always as ('SLF-' || lpad(serial_no::text, 6, '0')) stored unique,
  created_at timestamptz not null default now()
);

alter table public.person_serials enable row level security;

insert into public.person_serials (person_id)
select c.id from public.contacts c
on conflict (person_id) do nothing;

create or replace function public.ensure_person_serial()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.person_serials(person_id) values (new.id)
  on conflict (person_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_contacts_ensure_person_serial on public.contacts;
create trigger trg_contacts_ensure_person_serial
after insert on public.contacts
for each row execute function public.ensure_person_serial();

create table if not exists public.learning_states (
  person_id uuid not null references public.contacts(id) on delete cascade,
  node_id uuid not null references public.curriculum_nodes(id) on delete cascade,
  learning_status text not null default 'touched' check (learning_status in ('unseen','touched','understanding','practicing','embodied','reproducible','teachable')),
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  evidence_count integer not null default 0 check (evidence_count >= 0),
  current_blocker text,
  source_type text not null default 'system_inference' check (source_type in ('fact','self_report','ai_hypothesis','system_inference','human_review','third_party_evidence')),
  first_seen_at timestamptz,
  last_practiced_at timestamptz,
  next_review_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (person_id, node_id)
);

alter table public.learning_states enable row level security;
create index if not exists learning_states_person_status_idx on public.learning_states(person_id, learning_status);
create index if not exists learning_states_next_review_idx on public.learning_states(next_review_at) where next_review_at is not null;

create table if not exists public.capabilities (
  id uuid primary key default gen_random_uuid(),
  capability_key text not null unique,
  name text not null,
  category text not null check (category in ('knowledge','skill','experience','resource','trait','role_potential')),
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.capabilities enable row level security;
create index if not exists capabilities_category_idx on public.capabilities(category);

create table if not exists public.person_capabilities (
  person_id uuid not null references public.contacts(id) on delete cascade,
  capability_id uuid not null references public.capabilities(id) on delete cascade,
  capability_state text not null check (capability_state in ('has','wants_to_grow','can_help','can_teach','can_build')),
  evidence_level integer not null default 0 check (evidence_level >= 0 and evidence_level <= 5),
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  source_type text not null default 'self_report' check (source_type in ('fact','self_report','ai_hypothesis','system_inference','human_review','third_party_evidence')),
  verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (person_id, capability_id, capability_state)
);

alter table public.person_capabilities enable row level security;
create index if not exists person_capabilities_person_idx on public.person_capabilities(person_id);
create index if not exists person_capabilities_capability_idx on public.person_capabilities(capability_id, capability_state);

create table if not exists public.capability_evidence (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null references public.contacts(id) on delete cascade,
  capability_id uuid not null references public.capabilities(id) on delete cascade,
  source_event_id uuid references public.quest_events(id) on delete set null,
  evidence_type text not null default 'observation',
  source_type text not null default 'self_report' check (source_type in ('fact','self_report','ai_hypothesis','system_inference','human_review','third_party_evidence')),
  description text,
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.capability_evidence enable row level security;
create index if not exists capability_evidence_person_idx on public.capability_evidence(person_id, occurred_at desc);
create index if not exists capability_evidence_capability_idx on public.capability_evidence(capability_id, occurred_at desc);

create table if not exists public.encounter_recommendations (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null references public.contacts(id) on delete cascade,
  candidate_person_id uuid not null references public.contacts(id) on delete cascade,
  match_type text not null check (match_type in ('mentor','peer','collaborator','student','connector','unexpected')),
  reason text not null,
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  source_signals jsonb not null default '[]'::jsonb,
  status text not null default 'proposed' check (status in ('proposed','shown','accepted','skipped','met','useful','not_useful','expired')),
  generated_at timestamptz not null default now(),
  acted_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  check (person_id <> candidate_person_id)
);

alter table public.encounter_recommendations enable row level security;
create index if not exists encounter_recommendations_person_idx on public.encounter_recommendations(person_id, status, generated_at desc);
create index if not exists encounter_recommendations_candidate_idx on public.encounter_recommendations(candidate_person_id, generated_at desc);

create table if not exists public.encounter_feedback (
  id uuid primary key default gen_random_uuid(),
  recommendation_id uuid not null references public.encounter_recommendations(id) on delete cascade,
  person_id uuid not null references public.contacts(id) on delete cascade,
  feedback_type text not null check (feedback_type in ('accept','skip','met','useful','not_useful','follow_up')),
  note text,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.encounter_feedback enable row level security;
create index if not exists encounter_feedback_recommendation_idx on public.encounter_feedback(recommendation_id, occurred_at desc);

create table if not exists public.education_exchange_edges (
  id uuid primary key default gen_random_uuid(),
  from_person_id uuid not null references public.contacts(id) on delete cascade,
  to_person_id uuid not null references public.contacts(id) on delete cascade,
  relation_type text not null check (relation_type in ('learned_from','taught','coached_by','inspired_by','introduced_by','collaborated_with','supported_by','created_with')),
  source_type text not null default 'self_report' check (source_type in ('fact','self_report','ai_hypothesis','system_inference','human_review','third_party_evidence')),
  source_event_id uuid references public.quest_events(id) on delete set null,
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  check (from_person_id <> to_person_id)
);

alter table public.education_exchange_edges enable row level security;
create index if not exists education_exchange_from_idx on public.education_exchange_edges(from_person_id, occurred_at desc);
create index if not exists education_exchange_to_idx on public.education_exchange_edges(to_person_id, occurred_at desc);

alter table public.line_message_log add column if not exists delivery_mode text;
alter table public.line_message_log add column if not exists message_object_count smallint not null default 1;
alter table public.line_message_log add column if not exists billing_units integer not null default 0;
alter table public.line_message_log add column if not exists request_group_id uuid;
alter table public.line_message_log add column if not exists delivery_reason text;
alter table public.line_message_log add column if not exists cost_policy_decision text;
alter table public.line_message_log add column if not exists cost_metadata jsonb not null default '{}'::jsonb;

alter table public.line_message_log drop constraint if exists line_message_log_delivery_mode_check;
alter table public.line_message_log add constraint line_message_log_delivery_mode_check check (delivery_mode is null or delivery_mode in ('inbound','reply','push','multicast','broadcast','narrowcast','web','liff','system'));
alter table public.line_message_log drop constraint if exists line_message_log_message_object_count_check;
alter table public.line_message_log add constraint line_message_log_message_object_count_check check (message_object_count >= 0 and message_object_count <= 5);
alter table public.line_message_log drop constraint if exists line_message_log_billing_units_check;
alter table public.line_message_log add constraint line_message_log_billing_units_check check (billing_units >= 0);

create table if not exists public.line_cost_settings (
  id boolean primary key default true check (id = true),
  plan_name text,
  included_messages integer check (included_messages is null or included_messages >= 0),
  warning_ratio numeric not null default 0.8 check (warning_ratio > 0 and warning_ratio <= 1),
  hard_stop_ratio numeric check (hard_stop_ratio is null or hard_stop_ratio >= 1),
  currency text not null default 'JPY',
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.line_cost_settings enable row level security;
insert into public.line_cost_settings(id, metadata) values (true, '{"note":"Configure current LINE plan before enforcing budget actions"}'::jsonb)
on conflict (id) do nothing;

create or replace view public.line_monthly_usage
with (security_invoker = true)
as
select
  date_trunc('month', sent_at) as month,
  count(*) filter (where direction = 'outbound') as outbound_log_rows,
  coalesce(sum(billing_units) filter (where direction = 'outbound'), 0)::bigint as billing_units,
  count(*) filter (where direction = 'outbound' and delivery_mode = 'reply') as reply_rows,
  count(*) filter (where direction = 'outbound' and delivery_mode in ('push','multicast','broadcast','narrowcast')) as proactive_rows,
  coalesce(sum(message_object_count) filter (where direction = 'outbound'), 0)::bigint as message_objects
from public.line_message_log
group by 1;

comment on table public.person_serials is 'Stable public-friendly serial per canonical Human Graph person (contacts.id).';
comment on table public.learning_states is 'Per-person, per-curriculum-node learning state; understanding/practice/reproduction/teaching are distinct.';
comment on table public.capabilities is 'Canonical capability vocabulary across knowledge, skill, experience, resource, trait and role potential.';
comment on table public.person_capabilities is 'Evidence-aware person capability states; does not represent a fixed ability score.';
comment on table public.encounter_recommendations is 'Explainable People Match candidates; human approval is expected before introductions.';
comment on table public.education_exchange_edges is 'Time-aware Human Graph edges for learning, teaching, support, introductions and co-creation.';
comment on table public.line_cost_settings is 'Configuration for LINE Cost Optimizer; no hard enforcement until current plan is explicitly configured.';
comment on view public.line_monthly_usage is 'Monthly LINE delivery usage based on explicit billing_units logged by outbound delivery code.';
